---
# tasks file for pcs
- name: Place corosync config
  become: yes
  template:
    src: corosync
    dest: /etc/corosync/corosync.conf
    backup: yes
  with_items:
  - "{{ clusterNodes }}"
  register: corosync_conf
