---
# tasks file for pcs
- name: Place corosync config
  copy:
    src: /corosync
    dest: /etc/corosync/corosync.conf
    backup: yes

- name: set IP in corosync config
  replace:
    path: /etc/corosync/corosync.conf
    regexp: 'IWIP'
    replace: hostvars[inventory_hostname]['ansible_default_ipv4']['address']
