---
# tasks file for pcs
- name: Install required
  include_tasks: install.yml

- name: Configure pacemaker
  include_tasks: configure.yml

- name: Restart to make changes persist
  include_tasks: restart.yml
