---
# tasks file for pcs

- name: install pacemaker
  become: yes
  apt:
    name: ['pacemaker','corosync','pcs']
    state: latest

- name: set password for hacluster
  become: yes
  user:
    name: hacluster
    password: simplepass

- name: restart and enable corosync
  become: yes
  service:
    name: corosync
    state: restarted
    enabled: yes

- name: restart and enable pacemaker
  become: yes
  service:
    name: pacemaker
    state: restarted
    enabled: yes
