---
# tasks file for common
- name: Update repository and Upgrade packages
  become: yes
  apt:
    upgrade: dist
    update_cache: yes

- name: Setup timezone to Amsterdam
  become: yes
  timezone:
    name: Europe/Amsterdam
    state: latest


