---
# tasks file for common
- name: Update repository and Upgrade packages
  become: yes
  apt:
    upgrade: dist
    update_cache: yes

- name: Setup timezone to Amsterdam
  become: yes
  timezone:
    name: Europe/Amsterdam

- name: Set hosts
  become: yes
  blockinfile:
    backup: yes
    path: /etc/hosts
    block: "{{ hosts }}"
